[package]
name = "whitenoise"
version = "0.0.1"
description = "A secure messenger using MLS and Nostr"
authors = ["White Noise Authors"]
edition = "2021"

[lib]
name = "whitenoise_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dev-dependencies]
tempfile = "3.8.1"

[dependencies]
anyhow = "1.0"
env_logger = "0.11"
derive_more = { version = "1.0.0", features = ["from"] }
keyring = { version = "3.2.0", features = [
    "apple-native",
    "windows-native",
    "linux-native",
] }
lazy_static = "1.5"
log = "0.4"
nostr-sdk = { version = "0.34", features = ["ndb"] }
nostrdb = "0.3.4"
openmls = "0.6"
openmls_basic_credential = "0.3"
openmls_rust_crypto = "0.3"
openmls-sled-storage = { version = "0.0.1", git = "https://github.com/erskingardner/openmls-sled-storage", branch = "master" }
parking_lot = "0.12"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sled = "0.34"
tauri = { version = "2.0.0-rc", features = ["protocol-asset"] }
tauri-plugin-shell = "2.0.0-rc"
tauri-plugin-store = "2.0.0-rc"
tls_codec = "0.4"
tokio = { version = "1.40.0", features = ["full"] }


[patch.crates-io]
tungstenite = { git = "https://github.com/yukibtc/tungstenite-rs", branch = "tor" }

[profile.dev]
incremental = true

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2.0.0-rc"

[profile.release]
lto = true        # Enables link to optimizations
opt-level = "s"   # Optimize for binary size
codegen-units = 1 # Compiles crates one after another 
panic = "abort"   # Strip panic cleanup code
