name: "Release"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    uses: ./.github/workflows/build_linux.yml
    secrets: inherit

  build-macos:
    uses: ./.github/workflows/build_macos.yml
    secrets: inherit

  build-android:
    uses: ./.github/workflows/build_android.yml
    secrets: inherit

  # comment out for now
  # build-ios:
  #   uses: ./.github/workflows/build_ios.yml
  #   secrets: inherit

  create-release:
    needs: [build-linux, build-macos, build-android]
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: |
          echo "Artifact contents:"
          ls -R artifacts
          find artifacts -type f

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: "See the assets to download this version and install."
          files: |
            artifacts/**/*
